### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by dreispt** [OCA/pylint-odoo#14]
# Version 1.2.0
- [x] Use  [jshint](http://jshint.com/install/) (javascript linter, in package node)
  - W7903
- [x] You odoo field string don't need translate method `_` [example](https://github.com/OCA/sale-workflow/pull/213#discussion_r39856737)
  - W8103
- [x] License allowed
  - C8105
- [x] Deprecated _fields={}, _defaults={}, (other one?)
  - W8105
- [x] Use [restructuredtext_lint](https://pypi.python.org/pypi/restructuredtext_lint)
  - E7901
- [x] Methods with super expected
  - W8106
- [x] Deprecated `api.one` in v9 and recommended use `api.multi` in v8 more info [odoo/8527](https://github.com/odoo/odoo/pull/8527/files)
  - W8104
- [x] Check duplicate "XML Ids" in `ir.model.access.csv` files (at least if following the standard columns structure): I recently saw a bug fix where the lines where duplicated but the author forgot to change the ID of the second line, so it overwrites the former permission and the module doesn't work.
- [x] Check manifest version format: numbers have 5 positions and start with either 8.0, 9.0, etc: https://github.com/oca/maintainer-tools/blob/master/CONTRIBUTING.md#version-numbers
- [x] Redundant use xml_id with current_module.xml_id
- [x] Validation of newline to final of all source code files. [example](https://github.com/OCA/rma/pull/87/files/bd5b26881e9c07c4924bd6bf1405f53847bd58b4#r62880607)
- [x] Validate no-tabs in xml files of all source code files.
- [x] Methods that required even a translation (warning, errors...)
- [x] Same `field` assigned 2 times in xml `record`.
- [x] Dual compatibility with pylint2.0.0
- [x] Creation of record res.users without context="{'no_reset_password': True}
- [x] Duplicated xml fields tag id
# Version 1.3.x
- [x] Use `def _compute_*` methods for fields.functions of new api
- [x] avoid use of `self.cr.commit` or `self.env.commit` directly
- [x] avoid use of sql-injection
- [x] Enable and work the following https://github.com/PyCQA/pylint/issues/968
- [x] Avoid dummies `super(method)` without other sentence inherited
- [x] Deprecated `select = True` by `index = True`
- [x] Avoid use functional name equal to technical name for >=v8
# Backlog
- [ ] Avoid `console.log` from js https://github.com/OCA/maintainer-quality-tools/issues/335 worked from https://github.com/OCA/pylint-odoo/pull/97
- [ ] Enable new pylint check `unexpected-line-ending-format` with config expected_line_ending_format for `\n`
- [x] <s> Avoid double magic comment : `# coding: utf-8\n# coding: utf-8` or `#!/bin/python\n#!/bin/python` </s> It isn't a common error
- [ ] <s> Avoid filtered of boolean `obj.m2m_ids.filtered(lambda field: field.m2o_id.other_field is True)`. Use `obj.m2m_ids.filtered('field.m2o_id.other_field')` instead. </s> Maybe is not so good check
- [ ] <s> Avoid `obj.mapped('ids')` use obj.ids directly instead. <s/> It could be valid
- [ ] Avoid use of self.assertRaises better use self.assertRaisesRegex to catch exactly message of error
- [ ] Validate basic structure of README.rst with OCA template
- [ ] pylint enable E0213 - no-self-argument and E0211 - no-method-argument. (If you use empty or not use self in methods of class)
- [ ] pylint enable E1003 - Bad first argument %r given to super()
- [ ] pylint enable too-complex for cyclomatic complexity
- [ ] pylint enable docstring
- [x] Files xml, csv, yml... of openerp without a entry in manifest
- [ ] Files .py without a `import` in `__init__.py` files
- [ ] Singular names of new modules or class.
- [ ] Check for simple `<data>` element (with no `update` attribute).
- [ ] Use `<field name="".../>` first. Avoid `<field eval="value" name=""/>`
# Discussion
- [ ] <s>Detect bool field xml without a eval e.g. `<field name="boolean_field"="False"/>` use `<field name="boolean_field" eval="False"/>` instead. </s> To know if is a field boolean there is not a static way (Its a work for dynamic check)
- [ ] <s>Depends `base` in manifest is redundant.</s> Check if is really redundant
- [ ] <s>Documentation ./doc/index.rst</s> First add guidelines
- [ ] <s>Missing icon ./static/description/icon.png</s> After fix next issue https://github.com/odoo/odoo/issues/7507 
- [ ] <s> list, dict, tuple, with one element per line, append a comma to the last element.</s> too complex
- [ ] <s>Avoid to use yml for test (better use unitest)</s> Require argumentation
- [ ] <s>Use of `openerp.exceptions` instead of `assert`</s> Open discussion with @dreispt
- [ ] <s>Add a po-lint </s> Show many false errors
- [ ] <s> Fields declaration on top class. Check `In a Model attribute order should be` in https://github.com/oca/maintainer-tools/blob/master/CONTRIBUTING.md#field </s> The following change of the guidelines broken this future lint https://github.com/OCA/maintainer-tools/pull/199
- [ ]  <s>Check if button object functions return dicts/ir.actions or a variable</s> Out of scope for pylint-odoo maybe a runtime check
- [ ] <s>Cyclic depends (check before if odoo has this validation)</s> Out of scope for pylint-odoo maybe a runtime check
- [ ] <s>Use of fields undefined in model</s> Out of scope for pylint-odoo maybe a runtime check
- [ ] <s>`<record.. \n ... <field boolean...` without a eval</s> Out of scope for pylint-odoo maybe a runtime check

**Comment by sbidoul** [comment]
Another idea:

- [ ] check addon version numbers have 5 positions and start with either 8.0, 9.0, etc

**Comment by moylop260** [comment]
@sbidoul 
Idea added and I added other ones from: https://github.com/OCA/maintainer-quality-tools/issues/252

**Comment by moylop260** [comment]
@all
Feel free of create a new pull request to add new checks.
I've recorded when create next checks:
 - [Add pylint check to odoo lint - Adding deprecated attributes ](https://asciinema.org/a/26890)
 - [How to add a new check - adding licese allowed](https://asciinema.org/a/26889)

**Comment by max3903** [comment]
@moylop260 What does it mean when the checkbox is marked ? Is the feature included in the current release ? In the next one ? Already assigned to someone for development ?

**Comment by moylop260** [comment]
@max3903 
Yes, the checkbox marked is the feature included in the current release.
Now, I added the check number after of each checkbox marked.

Check box non-marked are "help wanted".

**Comment by dreispt** [comment]
`Avoid to use yml for test` - why? needs supporting argumentation.

**Comment by dreispt** [comment]
`Depends base in manifest is redudant`. Is it?

**Comment by dreispt** [comment]
`Use of openerp.exceptions instead of assert` Sounds opiniated. asserts are not meant to check exceptions, if they are activated some design assumptions went wrong.

**Comment by moylop260** [comment]
@dreispt 
> `Avoid to use yml for test` - why? needs supporting argumentation.

Ok, I got it
I changed the main message with:
- [ ] <s>Avoid to use yml for test (better use unitest)</s> Require argumentation


> `Depends base in manifest is redundant`. Is it?

I will create a video.
I saw a comment with this case in a old PR, but I don't found it.


> `Use of openerp.exceptions instead of assert` Sounds opiniated. asserts are not meant to check exceptions, if they are activated some design assumptions went wrong.

I we use in a odoo module:
```python
class MyModel(...
    ...
       assert "Message"
   ...
```
Better
```python
class MyModel(...
    ...
       openerp.exception("Message")
   ...
```

**Comment by max3903** [comment]
- [ ] Check for images keyword to include screenshots (displayed in the new Apps)

**Comment by moylop260** [comment]
> - [ ] Check for `images` keyword to include screenshots (displayed in the new Apps)

@max3903 
Are you talking about README files of each module?

**Comment by max3903** [comment]
@moylop260 no the images keyword in `__openerp__.py` to have screenshots displayed in Apps. Here is an example: https://www.odoo.com/apps/modules/8.0/crm_voip/

**Comment by moylop260** [comment]
@max3903 
Ok I got it
Then the sentence should be:
Add `images` key required in manifest.

Currently exists next check [manifest-required-key](https://github.com/OCA/pylint-odoo/blob/e00959f7132ffbd42b8389be91130d0187f5334f/pylint_odoo/checkers/no_modules.py#L117-L120)
You can add `images` item in next configuration file to check just in modules changed:
[pylint-modules-changed.cfg](https://github.com/OCA/maintainer-quality-tools/blob/c7a14d85d85a591999ea4570ca5de93fec46f7b8/travis/cfg/travis_run_pylint_pr.cfg#L14)

**Comment by max3903** [comment]
@moylop260 done. Thanks!

**Comment by moylop260** [comment]
@max3903  Thank you

**Comment by moylop260** [comment]
Avoid newline in `groups` tag of xml
```xml
..."groups">group1,
group2</..
```
Odoo don't support newline in `groups` tags
What do you think of this check?

**Comment by moylop260** [comment]
FYI I'll create the version 1.3.0 based on the last update of the main description here.

**Comment by moylop260** [comment]
Should we add the check to avoid multi-style xml-field definition to force use `<field name=***` instead of `<field ** name=*`

Different style (eval first):
```xml
<record model="ir.rule" id="access_rule">
    <field name="name">Access rule</field>
    <field name="model_id" ref="model_test_model"/>
    <field eval="1" name="perm_read"/>
    <field eval="0" name="perm_create"/>
    <field eval="0" name="perm_write"/>
    <field eval="0" name="perm_unlink"/>
    <field name="domain_force">[('user_ids','in',user.id)]</field>
</record>
```

Unique style
```xml
<record model="ir.rule" id="access_rule">
    <field name="name">Access rule</field>
    <field name="model_id" ref="model_test_model"/>
    <field name="perm_read" eval="1"/>
    <field name="perm_create" eval="0"/>
    <field name="perm_write" eval="0"/>
    <field name="perm_unlink" eval="0"/>
    <field name="domain_force">[('user_ids','in',user.id)]</field>
</record>
```

This allow us use a same standard style, and avoid large diff for changes of custom standards.
This check don't affect the process.

What do you think?

**Comment by dreispt** [comment]
@moylop260 I can't find a reason to do it otherwise. It's a *de facto* best practice. On the other hand I wonder if we're not going too far in the checks.

**Comment by moylop260** [comment]
@dreispt
Thanks for reply

You can see the roadmap of checks here to determine what are going too far for you, before to develop them.

FYI those checks are based on the guidelines and the reviewers comments in each pull request.

**Comment by dreispt** [comment]
Was the `<field name` order pointed out in a particular PR?

**Comment by moylop260** [comment]
A particular PR with the `<field name` changed is: [server-tools#351](https://github.com/OCA/server-tools/pull/351/files#diff-afc9b7ff0bf71838618e0a75b061283cR12)

A particular PR to pylint-odoo to check the order don't exists yet.
I need your feedback before to develop it

**Comment by blaggacao** [comment]
This is so cool! @moylop260 I think being a tiny little bit more verbose about the usage in the readme, would make me an immediate apostel.

**Comment by moylop260** [comment]
Your PRs are welcome!

**Comment by blaggacao** [comment]
Wonderful! This is not always the case 😄 However, I'm not "bought in" yet on this, sorry.

**Comment by dreispt** [comment]
@moylop260 I suggest you create a new Issue for each release to be done. Your welcome to keep a roadmap for what might be expected in other future releases, and/or keep a wishlist.

**Comment by lasley** [comment]
Might I suggest we move this over to a Github project for management of the backlog tasks? I'd be happy to move the tasks over if someone with permissions wants to create a "Roadmap", "Backlog", or "Icebox" project for me to drop the tasks in

**Comment by dreispt** [comment]
I', yet to see how projects fit into our workflow, but I created a "Roadmap" Project for us to play with. You're welcome to suggest any changes to the columns.

**Comment by lasley** [comment]
I don't guess they fit into the current workflow because they didn't used to exist. It seems to me that this ticket would be easier to handle with all the tasks left in backlog as individual project cards.

Turns out this idea was useless though - you need write access to the repo to even create cards. Sorry to waste your time @dreispt 😦  - it's been working well in some other repos, but I have write access. Didn't realize this limitation existed

**Comment by thomaspaulb** [comment]
Is it an idea to create a validation check for `@api.multi` methods that don't have `@api.one` or `self.ensure_one()`, but do have a line like `self.something = something` ?

**Comment by moylop260** [comment]
@thomaspaulb That is a good idea

**Comment by moylop260** [comment]
Closing since that new request of lints are created throughs issues
